AllCops:
  Excludes:
    - db/schema.rb
    - vendor/**/*
    - spec/**/*
    - tmp/**/*
    - config/initializers/secret_token.rb
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false