default: &default
  adapter: <%= Rails.application.secrets.default_db_adapter %>
  encoding: <%= Rails.application.secrets.default_db_encoding %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { Rails.application.secrets.default_db_pool.to_i } %>
  timeout: <%= Rails.application.secrets.default_db_timeout.to_i %>

development:
  <<: *default
  database: <%= Rails.application.secrets.database %>
  username: <%= Rails.application.secrets.username %>
  password: <%= Rails.application.secrets.password %>

production:
  <<: *default
  database: <%= Rails.application.secrets.database %>
  username: <%= Rails.application.secrets.username %>
  password: <%= Rails.application.secrets.password %>