default: &default
  adapter: <%= ENV['default_db_adapter'] %>
  encoding: <%= ENV['default_db_encoding'] %>
  pool: <%= ENV['default_db_pool'].to_i %>
  timeout: <%= ENV['default_db_timeout'].to_i %>

development:
  <<: *default
  database: <%= ENV['database'] %>
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>

production:
  <<: *default
  database: <%= ENV['database'] %>
  username: <%= ENV['username'] %>
  password: <%= ENV['password'] %>